# Generated by Django 4.1.2 on 2022-10-29 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('universe', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('abilities', models.ManyToManyField(to='main.ability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hero')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Battle Date')),
                ('location', models.CharField(choices=[('B', 'Earth'), ('L', 'Apocalypse'), ('D', 'Asgard')], default='B', max_length=1)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hero')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
